"""initial_schema

Revision ID: 9150422eefed
Revises: 
Create Date: 2026-03-03 23:17:58.795888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9150422eefed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('componentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_componentes_id'), 'componentes', ['id'], unique=False)
    op.create_table('pedidos_estandar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=False),
    sa.Column('cliente_correo', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_estandar_id'), 'pedidos_estandar', ['id'], unique=False)
    op.create_table('pedidos_personalizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=False),
    sa.Column('cliente_correo', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_definido', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('token_confirmacion', sa.String(length=64), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_confirmacion')
    )
    op.create_index(op.f('ix_pedidos_personalizados_id'), 'pedidos_personalizados', ['id'], unique=False)
    op.create_table('pedido_personalizado_componentes',
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('componente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['componente_id'], ['componentes.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_personalizados.id'], ondelete='CASCADE')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estilo_tejido', sa.String(length=100), nullable=True),
    sa.Column('color_hilo', sa.String(length=100), nullable=True),
    sa.Column('digen', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('fotos_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_producto_id'), 'fotos_producto', ['id'], unique=False)
    op.create_table('items_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_estandar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_fotos_producto_id'), table_name='fotos_producto')
    op.drop_table('fotos_producto')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_table('pedido_personalizado_componentes')
    op.drop_index(op.f('ix_pedidos_personalizados_id'), table_name='pedidos_personalizados')
    op.drop_table('pedidos_personalizados')
    op.drop_index(op.f('ix_pedidos_estandar_id'), table_name='pedidos_estandar')
    op.drop_table('pedidos_estandar')
    op.drop_index(op.f('ix_componentes_id'), table_name='componentes')
    op.drop_table('componentes')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
